{% set name = "pyshtools" %}
{% set version = "4.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cb15fe572f45c4979f3e1dd3e413446c5e375f46f5b6cd7bc0abd76bae5cb551

build:
  number: 2
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - setuptools
    - numpy
    - fftw >=3.3.8
    - liblapack >=3.8
    - openblas
  run:
    - python
    - numpy
    - fftw >=3.3.8
    - liblapack >=3.8
    - openblas
    - scipy >=0.14.0
    - matplotlib-base >=3.3
    - astropy
    - xarray
    - requests
    - gmt >=6.1.1
    - pygmt >=0.2
    - pooch >=1.1
    - tqdm
    - cartopy >=0.18

test:
  requires:
    - make
    - tar
    - wget
  imports:
    - pyshtools
  commands:
    - wget https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    - tar -xvf {{ name }}-{{ version }}.tar.gz
    - cd {{ name }}-{{ version }}
    - make -C examples/python -f Makefile no-timing

about:
  home: https://github.com/SHTOOLS/SHTOOLS
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Tools for working with spherical harmonics

  description: |
    SHTOOLS/pysthools is a Fortran-95/Python library that can be used to
    perform spherical harmonic transforms, multitaper spectral analyses on the
    sphere, expansions of functions into Slepian bases, and standard operations
    on global gravitational and magnetic field data.
  doc_url: https://shtools.github.io/SHTOOLS/
  dev_url: https://github.com/SHTOOLS/SHTOOLS

extra:
  recipe-maintainers:
    - megies
    - moorepants
    - markwieczorek
